name: Lint/Build/Test/Cov

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  main:
    uses: dydxprotocol/actions/.github/workflows/v3-lint-build-test-cov.yml@main
    secrets: inherit
